activation: gelu
attn_factor: 5
attn_time_windows: 1
base_lr: 0.0005
class_loss_imp: 0.1
d_ff: 20
d_layers: 3
d_model: 20
d_queries_keys: 20
d_values: 20
d_x: 1
d_yc: 106
d_yt: 106
decay_factor: 0.25
dropout_attn_matrix: 0.0
dropout_attn_out: 0.0
dropout_emb: 0.2
dropout_ff: 0.3
dropout_qkv: 0.0
e_layers: 3
embed_method: spatio-temporal
global_cross_attn: performer
global_self_attn: performer
init_lr: 1.0e-10
initial_downsample_convs: 0
intermediate_downsample_convs: 0
l2_coeff: 1.0e-06
learning_rate: 0.001
linear_shared_weights: false
linear_window: 0
local_cross_attn: performer
local_self_attn: performer
loss: mse
max_seq_len: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  EAAAAAAAAAA=
n_heads: 1
norm: batch
null_value: -1
pad_value: null
performer_kernel: relu
performer_redraw_interval: 100
performer_relu: true
pos_emb_type: abs
recon_loss_imp: 0.0
recon_mask_drop_full: 0.05
recon_mask_drop_seq: 0.2
recon_mask_drop_standard: 0.1
recon_mask_max_seq_len: 5
recon_mask_skip_all: 1.0
start_token_len: 0
time_emb_dim: 6
use_final_norm: true
use_given: true
use_revin: false
use_seasonal_decomp: false
use_shifted_time_windows: false
use_space: true
use_time: true
use_val: true
verbose: true
warmup_steps: 0
